-- AlterTable
ALTER TABLE "Container" ALTER COLUMN "size" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "size" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Warehouse" ALTER COLUMN "capacity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "current_capacity" SET DATA TYPE DOUBLE PRECISION;
